import { useEffect, useState, useCallback } from "react";
import { useNavigate } from "react-router-dom";
import { Activity, Sparkles, Workflow as WorkflowIcon, Clock, TrendingUp } from "lucide-react";
import Layout from "../components/Layout";
import StatCard from "../components/StatCard";
import ActivityTimeline from "../components/ActivityTimeline";
import DemoButton from "../components/DemoButton";
import { api } from "../services/api";

export default function Dashboard() {
  const navigate = useNavigate();
  const [stats, setStats] = useState(null);
  const [events, setEvents] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  const loadAll = useCallback(async () => {
    try {
      const [statsData, activityData] = await Promise.all([
        api.getDashboardStats(),
        api.listActivity(8),
      ]);
      setStats(statsData);
      setEvents(activityData);
      setError(null);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    loadAll();
  }, [loadAll]);

  const handleDemoEvent = (event) => {
    setEvents((prev) => [...prev, event].slice(-8));
  };

  const handleDemoComplete = (sessionId) => {
    loadAll();
    // Hand off to Discovered Workflows: it will run repetition detection +
    // the Gemini intent/workflow generation for this session and display
    // the resulting suggestion, completing the full pipeline.
    navigate("/discovered", { state: { sessionId } });
  };

  return (
    <Layout
      title="Dashboard"
      subtitle="Your work teaches the computer how to automate it."
      actions={<DemoButton onEvent={handleDemoEvent} onComplete={handleDemoComplete} />}
    >
      {error && (
        <div className="mb-6 rounded-xl border border-rose-400/30 bg-rose-400/10 px-4 py-3 text-sm text-rose-400">
          Could not reach the backend ({error}). Is it running on the expected port?
        </div>
      )}

      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-4 mb-8">
        <StatCard
          label="Total activities"
          value={loading ? "–" : stats?.total_activities ?? 0}
          icon={Activity}
          accent="violet"
        />
        <StatCard
          label="Workflows discovered"
          value={loading ? "–" : stats?.workflows_discovered ?? 0}
          icon={Sparkles}
          accent="teal"
        />
        <StatCard
          label="Active automations"
          value={loading ? "–" : stats?.active_automations ?? 0}
          icon={WorkflowIcon}
          accent="violet"
        />
        <StatCard
          label="Time saved"
          value={loading ? "–" : `${stats?.time_saved_minutes ?? 0}m`}
          sublabel="estimated"
          icon={Clock}
          accent="teal"
        />
        <StatCard
          label="Success rate"
          value={loading ? "–" : `${stats?.success_rate ?? 0}%`}
          sublabel={`${stats?.successful_executions ?? 0} runs`}
          icon={TrendingUp}
          accent="amber"
        />
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-5">
        <div className="lg:col-span-2 rounded-2xl border border-base-border bg-base-surface p-6">
          <div className="flex items-center justify-between mb-5">
            <h2 className="font-display font-semibold text-ink-100">Recent activity</h2>
            <span className="flex items-center gap-1.5 text-[12px] text-ink-500">
              <span className="w-1.5 h-1.5 rounded-full bg-teal-400 pulse-dot" />
              Live
            </span>
          </div>
          <ActivityTimeline
            events={events}
            emptyLabel="No activity yet — click Simulate to generate a demo workflow."
          />
        </div>

        <div className="rounded-2xl border border-base-border bg-base-surface p-6">
          <h2 className="font-display font-semibold text-ink-100 mb-2">How this works</h2>
          <ol className="space-y-3 text-[13px] text-ink-500 leading-relaxed list-decimal list-inside">
            <li>WorkFlowOS observes activity across your apps.</li>
            <li>It groups events and detects repeated sequences.</li>
            <li>Gemini explains the intent behind the pattern.</li>
            <li>You review and approve the generated workflow.</li>
            <li>The automation engine runs it — and learns from results.</li>
          </ol>
          <div className="mt-5 pt-5 border-t border-base-border">
            <p className="text-[12px] text-ink-500">
              No Gmail, Slack or CRM credentials needed for this demo — activity is generated by a
              realistic simulation layer that mirrors the real event schema.
            </p>
          </div>
        </div>
      </div>
    </Layout>
  );
}
